language: node_js
node_js:
  - "10"
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
  - node_modules
  - ~/.cache

install:
  - npm install

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: AKIAWJQ2KT3RWAZ7KEP7
  secret_access_key:
    secure: "BXT624y1c5C6Tf42lY1q0FfOYgY+AHLqAmWVtNwMM3LR0mHXJUCS9WENf58++PFVWvJVY8xg8M2gsGomEM4lDiBgk+FnVm86nYp2HwWkuinQP3oHoWdCCHy9rfXJtvyfzi28LfvEJBFwJS/qxqAijcP9C4VBbKPAclL94VbbYTZt1Xg8FGYkFza2b7PVa5X0q3KBz2xZGHBvdV2zk+wxHf7tF4bQ05n1Dodfbf62S8U9OVZG1O2agTQ9QW81abjNHtPnAzkTEyHC1XpQwCk4B9dQDf7b4EMscbXbVSi4VMWu1xUUxmMKuySdNsVF1Cfg2KE6jTxshU6bEjSxRvG0iaZJH5YMkow7HYjOpn0Xf82ZHaKtCIFttJb6f0d9+KUGKkhkE/wr+gxNCg3+WfmCi33F08oeiHLSHbtxCNdEJScCYdlUOrHAF8wG89sL8tYsFXjy2fzQsV7AY29GEDApE5nTKgQ1x2S15CkzXjL5Js5JSAyeOVcwEnywc9znyic+izsN+kGMv82Uiom9YEozcO0WNDHy3BIta4mm1GTFLeXv25NSEBwJwscgpVY/hsqhJaeXlLlliyzoBKPd51OjSoqCt+bRTvf1Gvtj4JpOxVPoItl85VZXsxWzLvo3vZkiz9kDz2EjTSYCAXocJNEuutYuFAEnbFUjWNcmuuU1mDM="
  bucket: "nubank-challenge-front"
  skip_cleanup: true
  region: us-east-1
  local_dir: dist/
  acl: public_read
branches:
  only:
  - master
