language: node_js
node_js:
  - "10"
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
  - node_modules
  - ~/.cache

install:
  - npm install

script:
  - npm run test:unit
  - npm run test:cypress
  - npm run build

deploy:
  provider: s3
  access_key_id: AKIAWJQ2KT3RWAZ7KEP7
  secret_access_key:
    secure: "TzNbgDb+m3kcWVMxiWyNolspaCPk7sbkn3BVkclejqati4RDS3bmYEtSyNjWuYWSIi73orXCg1M9pl16PCRgHs29RozsMRR9lztOJvzewH7qAF+dGWVFac4znHOKdriqiNBIMoFHE/rOisopPC3R5S9X+T3xPIYZStf1nMbISHhdrJPZJfyQpCljepIee24ChvgtpufO2lFlLcpWeFhhZ8tv97MpsRIEhv/Dw5Xbp8+WiCFSocGWw/je5QAYrwPsfoh+R9bnFNR3dBzIJFPSTSKPxwBlEjbUMc7jkD9NXGQbVYTwa54PQVf7IrGOygM1q/HgTZuJtHuOV1SXuT59OEVtOvoEGelnV9ZsM1VRD+blp59VNQUEufUqttz4IEnYYrio+IZWVpDZvyM+cljlxwx89QHt2oqHam+XTtfIZcqu2XBQSLdXH8qLbtwt+OmhgR5oljEdtFtcyaMUIytmiWx2TPgwaG69GNBIdcth3WUMw/rY8+G222R8yPy51rY9rFiecBnH57RTH82MSvd7+7KUFhC378f1+KUevknKun2xrIhhqQPt/VF/bCWcfQ6A0wwDnsmnQsd4m61Vnk2fP3RNbhoNgl5dS69Co3cooZA0Bw+OZlURJBrEa2yMVFy04/KCdKEk1IE8dIMvv7NTJuHuqgyUu3guHCNrJ0lXF0o="

  bucket: "nubank-challenge-front"
  skip_cleanup: true
  region: us-east-1
  local_dir: dist/
  acl: public_read
branches:
  only:
  - master
